services:
  db:
    image: postgis/postgis:latest
    restart: always
    networks:
      - "internal"
    ports:
      - "5432:5432"
    env_file:
      - ./env/db.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: always
    networks:
      - "external"
    ports:
      - "6379:6379"
  tethys:
    image: webinar-test-image:latest
    build: .
    restart: always
    depends_on:
      - "db"
      - "redis"
    networks:
      - "internal"
      - "external"
    ports:
        - "80:80"
    env_file:
      - ./env/tethys.env
    volumes:
      - ./data/tethys:/var/lib/tethys_persist
      - ./logs/tethys:/var/log/tethys
networks:
  internal:
    internal: true
  external: